-- =====================================================
-- CREAR TABLA ADMINISTRADORES
-- =====================================================
CREATE TABLE IF NOT EXISTS public.administradores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  nombre TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- POLÍTICAS RLS
-- =====================================================
ALTER TABLE public.administradores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read administradores" ON public.administradores FOR SELECT USING (true);

-- =====================================================
-- INSERTAR ADMINISTRADOR
-- Usuario: admin
-- Password: admin123
-- =====================================================
INSERT INTO public.administradores (usuario, password_hash, nombre) VALUES
  ('admin', 'YWRtaW4xMjM=', 'Administrador');