-- =====================================================
-- BASE DE DATOS - THE GORDO RESTAURANT RESERVAS
-- =====================================================

-- =====================================================
-- TABLA: ADMINISTRADORES
-- =====================================================
CREATE TABLE IF NOT EXISTS public.administradores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  nombre TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- TABLA: MESAS
-- =====================================================
CREATE TABLE IF NOT EXISTS public.mesas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero INTEGER NOT NULL UNIQUE,
  capacidad INTEGER NOT NULL CHECK (capacidad >= 1 AND capacidad <= 20),
  ubicacion TEXT,
  estado TEXT NOT NULL DEFAULT 'disponible' CHECK (estado IN ('disponible', 'ocupada', 'bloqueada')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- TABLA: RESERVAS
-- =====================================================
CREATE TABLE IF NOT EXISTS public.reservas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_id BIGINT NOT NULL REFERENCES public.mesas(id) ON DELETE CASCADE,
  cliente_nombre TEXT NOT NULL,
  cliente_tel TEXT NOT NULL,
  cliente_email TEXT NOT NULL,
  fecha DATE NOT NULL,
  hora TEXT NOT NULL,
  num_personas INTEGER NOT NULL CHECK (num_personas >= 1 AND num_personas <= 20),
  estado TEXT NOT NULL DEFAULT 'confirmada' CHECK (estado IN ('confirmada', 'cancelada')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- TABLA: HORARIOS
-- =====================================================
CREATE TABLE IF NOT EXISTS public.horarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dia_semana INTEGER NOT NULL CHECK (dia_semana >= 0 AND dia_semana <= 6),
  hora_inicio TEXT NOT NULL,
  hora_fin TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- BASE DE DATOS - THE GORDO RESTAURANT RESERVAS
-- =====================================================

-- =====================================================
-- POLÍTICAS RLS (Row Level Security)
-- =====================================================

-- Habilitar RLS
ALTER TABLE public.mesas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.horarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.administradores ENABLE ROW LEVEL SECURITY;

-- Políticas para administradores - solo lectura pública para login
CREATE POLICY "Anyone can read administradores" ON public.administradores FOR SELECT USING (true);

-- Políticas para mesas - everyone can read, everyone can write
CREATE POLICY "Anyone can read mesas" ON public.mesas FOR SELECT USING (true);
CREATE POLICY "Anyone can insert mesas" ON public.mesas FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update mesas" ON public.mesas FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete mesas" ON public.mesas FOR DELETE USING (true);

-- Políticas para reservas - everyone can read, everyone can write
CREATE POLICY "Anyone can read reservas" ON public.reservas FOR SELECT USING (true);
CREATE POLICY "Anyone can insert reservas" ON public.reservas FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update reservas" ON public.reservas FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete reservas" ON public.reservas FOR DELETE USING (true);

-- Políticas para horarios - everyone can read, everyone can write
CREATE POLICY "Anyone can read horarios" ON public.horarios FOR SELECT USING (true);
CREATE POLICY "Anyone can insert horarios" ON public.horarios FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update horarios" ON public.horarios FOR UPDATE USING (true);
CREATE POLICY "Anyone can delete horarios" ON public.horarios FOR DELETE USING (true);

-- =====================================================
-- ÍNDICES PARA MEJOR RENDIMIENTO
-- =====================================================
CREATE INDEX idx_mesas_numero ON public.mesas(numero);
CREATE INDEX idx_reservas_fecha ON public.reservas(fecha);
CREATE INDEX idx_reservas_mesa_fecha ON public.reservas(mesa_id, fecha);
CREATE INDEX idx_horarios_dia ON public.horarios(dia_semana);

-- =====================================================
-- DATOS DE EJEMPLO - MESAS
-- =====================================================
INSERT INTO public.mesas (numero, capacidad, ubicacion, estado) VALUES
  (1, 2, 'Interior', 'disponible'),
  (2, 2, 'Interior', 'disponible'),
  (3, 4, 'Interior', 'disponible'),
  (4, 4, 'Interior', 'disponible'),
  (5, 6, 'Terraza', 'disponible'),
  (6, 8, 'Terraza', 'disponible')
ON CONFLICT (numero) DO NOTHING;

-- =====================================================
-- DATOS DE EJEMPLO - HORARIOS
-- =====================================================
INSERT INTO public.horarios (dia_semana, hora_inicio, hora_fin, activo) VALUES
  (0, '12', '20', true),
  (1, '12', '21', true),
  (2, '12', '21', true),
  (3, '12', '21', true),
  (4, '12', '21', true),
  (5, '12', '22', true),
  (6, '12', '22', true)
ON CONFLICT DO NOTHING;

-- =====================================================
-- DATOS DE EJEMPLO - ADMINISTRADOR
-- Usuario: admin
-- Password: admin123
-- =====================================================
INSERT INTO public.administradores (usuario, password_hash, nombre) VALUES
  ('admin', 'YWRtaW4xMjM=', 'Administrador')
ON CONFLICT (usuario) DO NOTHING;